<?php

namespace Geekdoos\DoctorsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AntecedentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntecedentRepository extends EntityRepository
{
}
