<?php

namespace Geekdoos\DoctorsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
	public function updateBy($key, $value)
    {
        $qB = $this->getEntityManager()->createQueryBuilder()
        	->update('GeekdoosDoctorsBundle:config', 'c')
            ->set('c.theValue', '?1')
            ->where('c.theKey = ?2')
            ->setParameter(1, $value)
            ->setParameter(2, $key);
         
        return $qB->getQuery()->execute();
    }
}
